console.log(document.querySelector(".box"))
console.log(document.querySelector(".box").innerHTML)
console.log(document.querySelector(".container").innerHTML)
console.log(document.querySelector(".box").innerText)
console.log(document.querySelector(".container").innerText)
console.log(document.querySelector(".container").outerHTML)
console.log(document.querySelector(".box").outerHTML)
console.log(document.querySelector(".box").outerText)
console.log(document.querySelector(".container").outerText)
console.log(document.querySelector(".box").tagName)
console.log(document.querySelector(".box").nodeName)
console.log(document.querySelector(".box").firstChild.nodeName)
console.log(document.querySelector(".container").children[1]);
console.log(document.querySelector(".box").textContent)
// console.log(document.querySelector(".box").hidden = true)
console.log(document.querySelector(".box").innerHTML="Hey I am your boss")
console.log(document.querySelector(".box").innerTex="Hey I am your Ravi boss")

console.log(document.querySelector(".box").hasAttribute("style"))
console.log(document.querySelector(".box").getAttribute("style"))
document.querySelector(".box").setAttribute("style","display: inline")
document.querySelector(".box").removeAttribute("style")
console.log(document.querySelector(".box").dataset)